LRRCEresource/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

urlpatterns += [
    url(r'^catalog/', include('catalog.urls'), name='home'),
    url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/urls.py
from django.conf.urls import url

from .views import OrganismListView, OrganismDetailView, index

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^organisms/$', OrganismListView.as_view(), name='navigation'),
    url(r'^organism/(?P<pk>[0-9]+)/$', OrganismDetailView.as_view(), name='organism'),
]

catalog/models.py
from django.db import models
from django.urls import reverse # Used to generate urls by reversing the url patterns

class Organism(models.Model):
    """
    Model to define the organisms table, which contains only an id field and organism name.
    
    Primary key - ID field autocreated
    Name - Organism name
    Taxonomic group - Broad taxonomic group that organism belongs to (i.e. Mammal, Urochordates)
    """
    
    name = models.CharField(max_length=50)
    taxonomic_group = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        """
        Returns the url to access a particular organism instance
        """
        return reverse('organism', kwargs={'pk': self.pk})

    
class Gene(models.Model):
    """
    Model to define the genes table
    
    Primary key - ID field autocreated
    Foreign key - organism (links to organism table)
    Title - Short title of gene (i.e. KERA_HUMAN)
    Name - List of names (as seen on site)
    Existence - State of protein existence (i.e. Evidence at transcript level)
    LRRCE seq - ONLY sequence of LRRCE motif
    UniProt seq - Sequence from UniProt
    NCBI seq    -     "     "   NCBI
    Genbank seq -     "     "   Genbank
    Class field - Class of protein (i.e. Asporin - class I, Lumican - class IIa)
    """
    
    organism = models.ForeignKey(Organism, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    name = models.CharField(max_length=255)
    existence = models.CharField(db_column='Protein Existence', max_length=255)
    lrrce_seq = models.CharField(db_column='LRRCE sequence', max_length=255)
    uniprot_seq = models.TextField(blank=True)
    ncbi_seq = models.TextField(blank=True)
    genbank_seq = models.TextField(blank=True)
    genscan_pred_seq = models.TextField(blank=True, db_column='Genscan Prediction')
    ensembl_seq = models.TextField(blank=True)
    class_field = models.CharField(max_length=5)
    
    def __str__(self):
        return self.title
    
    
class Link(models.Model):
    """
    Model to define links table
    
    Primary key - ID field autocreated
    Foreign key - gene (links to gene table)
                - organism (links to organism table)
    Link accession  - Accession code of link (i.e. P01938)
    Link type - UniProt, NCBI, ENSEMBL etc.
    Address - url of link
    Primary - Boolean field, designates primary or other link (True or False respectively)
    """
    
    link_accession = models.CharField(max_length=50)
    gene = models.ForeignKey(Gene, on_delete=models.CASCADE)
    organism = models.ForeignKey(Organism, on_delete=models.CASCADE)
    link_type = models.CharField(max_length=50)
    address = models.TextField()
    primary = models.BooleanField(default=False)
    
    def __str__(self):
        return self.link_accession

catalog/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.
from .models import Organism, Gene, Link

def index(request):
    """
    View function for homepage of site
    """
    
    # Render the HTML template index.html
    
    return render(
        request,
        'index.html',
    )
    
    
class OrganismListView(generic.ListView):

    model = Organism
    context_object_name = 'organism_list'
    template_name = 'gene_list'
    


class OrganismDetailView(generic.DetailView):
    
    model = Organism
    context_object_name = 'org_details'
    template_name = 'catalog/org_details.html'


class PrimaryLinkView(generic.ListView):
    
    model = Link
    context_object_name = 'prim_links'
    template_name = 'catalog/org_details.html'
    
    

catalog/templates/base-menu.html
<!doctype html>

<html lang="en-UK">
	<head>
		<title>{% block title %}{% endblock %}</title>
		<meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet">
	</head>

	<body>
        
        {% block menubar %}
        <!-- Menu bar across top of page -->
        <ul id="menu">
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'navigation' %}">Organisms</a></li>
            <!--
            <li><a href="#LRRCE-PUBS">Publications</a></li>
            <li><a href="LRRCE-USEFUL">Useful Links</a></li>
            <li><a href="LRRCE-CONTACT">Contact Us</a></li>     -->
        </ul>
        {% endblock %}
        
        {% block content %}{% endblock %}
        
        
	</body>
</html>

catalog/templates/catalog/org_details.html
{% extends "base-menu.html" %}

{% block title %}{{ org_details.name }}{% endblock %}

{% block content %}


<h1>{{ org_details.name }}</h1>

    {% block imagetable %}
        <!-- Image table. In future this will contain links to page sections -->
        
        {% if org_details.name == 'Human' %}
        <table>
            <tr>{% load static %}
                <td class="tab_row_head">Chr 9q22</td>
                <td><a href="#h201"><img src="{% static 'img/SLRP-buttons/ECM2.png' %}"></a></td>
                <td><a href="#h202"><img src="{% static 'img/SLRP-buttons/ASPN.png' %}"></a></td>
                <td class="tab_empty_cell"></td>
                <td><a href="#h203"><img src="{% static 'img/SLRP-buttons/OMD.png' %}"></a></td>
                <td><a href="#h204"><img src="{% static 'img/SLRP-buttons/OGN.png' %}"></a></td>
            </tr>
            <tr>
                <td class="tab_row_head">Chr 12q21</td>
                <td class="tab_empty_cell"></td>
                <td><a href="#h205"><img src="{% static 'img/SLRP-buttons/DCN.png' %}"></a></td>
                <td><a href="#h206"><img src="{% static 'img/SLRP-buttons/LUM.png' %}"></a></td>
                <td><a href="#h207"><img src="{% static 'img/SLRP-buttons/KERA.png' %}"></a></td>
                <td><a href="#h208"><img src="{% static 'img/SLRP-buttons/EPYC.png' %}"></a></td>
            </tr>
            <tr>
                <td class="tab_row_head">Chr 1q32</td>
                <td class="tab_empty_cell"></td>
                <td class="tab_empty_cell"></td>
                <td><a href="#h209"><img src="{% static 'img/SLRP-buttons/FMOD.png' %}"></a></td>
                <td><a href="#h210"><img src="{% static 'img/SLRP-buttons/PRELP.png' %}"></a></td>
                <td><a href="#h211"><img src="{% static 'img/SLRP-buttons/OPTC.png' %}"></a></td>
            </tr>
            <tr>
                <td class="tab_row_head">Chr Xq28</td>
                <td><a href="#h212"><img src="{% static 'img/SLRP-buttons/ECMX.png' %}"></a></td>
                <td><a href="#h213"><img src="{% static 'img/SLRP-buttons/BGN.png' %}"></a></td>
                <td class="tab_empty_cell"></td>
                <td class="tab_empty_cell"></td>
                <td class="tab_empty_cell"></td>
            </tr>
        </table>
        {% endif %}
    {% endblock %}
        
        {% for gene in org_details.gene_set.all %}
            <!-- First sub-heading -->
            <h2 class="{{ gene.class_field }}" id="h201">{{ gene.title }}</h2>
            
            <!-- Table with information for each gene -->
            <table>
                <tr>
                    <td class="tab2_left"><i>Name</i></td>
                    <td>{{ gene.name }}</td>
                </tr>
                <tr>
                    <td class="tab2_left"><i>Protein Existence</i></td>
                    <td>{{ gene.existence }}</td>
                </tr>
                <tr>
                    <td class="tab2_left_head"><i>Primary Links</i></td>
                </tr>
                <tr>
                    {% for link in gene.link_set.all %}
                        {% if link.primary %}
                    <td class="tab2_left">{{ link.link_type }}</td>
                    <td><a href="{{ link.link_address }}">{{ link.link_accession }}</a></td>
                </tr>   {% endif %}
                    {% endfor %}
                <tr>
                    <td class="tab2_left_head"><i>Other Links</i></td>
                </tr>
                <tr>
                    {% for link in gene.link_set.all %}
                        {% if link.primary %}
                        {% else %}
                            
                    <td class="tab2_left">{{ link.link_type }}</td>
                    <td><a href="{{ link.link_address }}">{{ link.link_accession }}</a></td>
                </tr>
                        {% endif %}
                    {% endfor %}        
                <tr>
                    <td class="tab2_left_fasta"><i>LRRCE Sequence</i></td>
                    <td class="fasta">{{ gene.lrrce_seq }}
                    </td>
                </tr>
                {% if gene.uniprot_seq %}        
                <tr>
                    <td class="tab2_left_fasta"><i>FASTA<br>(uniprot)<br></i></td>
                    <td class="fasta">{{ gene.uniprot_seq }}
                    </td>
                </tr>
                {% endif %}
                {% if gene.ncbi_seq %}
                <tr>
                    <td class="tab2_left_fasta"><i>FASTA<br>(NCBI)<br></i></td>
                    <td class="fasta">{{ gene.ncbi_seq }}
                    </td>  
                </tr>
                {% endif %}
                {% if gene.genbank_seq %}
                <tr>
                    <td class="tab2_left_fasta"><i>FASTA<br>(genbank)<br></i></td>
                    <td class="fasta">{{ gene.genbank_seq }}
                    </td>
                </tr>
                {% endif %}
                {% if gene.genscan_pred_seq %}
                <tr>
                    <td class="tab2_left_fasta"><i>FASTA<br>(genscan prediction)<br></i></td>
                    <td class="fasta">{{ gene.genscan_pred_seq }}
                    </td>
                </tr>
                {% endif %}
                {% if gene.ensembl_seq %}
                <tr>
                    <td class="tab2_left_fasta"><i>FASTA<br>(ensembl)<br></i></td>
                    <td class="fasta">{{ gene.ensembl_seq }}
                    </td>
                </tr>
                {% endif %}
                <tr>
                    <td class="tab2_left_head"><a href="#top">Back to Top</a></td>
                </tr>
            </table> 
        {% endfor %}
    
{% endblock %}

catalog/templates/catalog/organism_list.html
{% extends "base-menu.html" %}
		{% block title %}Organisms Page{% endblock %}
		
        
        {% block content %}
        <h1>Organisms</h1>
        
        <p>This page shows a list of all the organisms whose LRRCE SLRP information is contained in this resource.</p>
        
        {% load catalog_extras %}
        <div>
            <div class="double_div" id="mammals">
                <h3>Mammals</h3>
                
                {% for org in organism_list|filter_by_taxonomy:'Mammal' %}
                    <ul><a href="{{ org.get_absolute_url }}">{{ org.name }}</a></ul>
                {% endfor %}
            </div>
        </div>

            <div class="single_div" id="fish">
                <h3>Fish</h3>

                {% for org in organism_list|filter_by_taxonomy:'Fish' %}
                    <ul><a href="{{ org.get_absolute_url }}">{{ org.name }}</a></ul>
                {% endfor %}  
            </div>
        </div>
        
        <div>
            <div class="single_div" id="amphibians">
                <h3>Amphibians</h3>

                {% for org in organism_list|filter_by_taxonomy:'Amphibian' %}
                    <ul><a href="{{ org.get_absolute_url }}">{{ org.name }}</a></ul>
                {% endfor %}
            </div>


            <div class="single_div" id="birds">
                <h3>Birds</h3>

                {% for org in organism_list|filter_by_taxonomy:'Bird' %}
                    <ul><a href="{{ org.get_absolute_url }}">{{ org.name }}</a></ul>
                {% endfor %}
            </div>


            <div class="single_div" id="urochordates">
                <h3>Urochordates</h3>

                {% for org in organism_list|filter_by_taxonomy:'Urochordates' %}
                    <ul><a href="{{ org.get_absolute_url }}">{{ org.name }}</a></ul>
                {% endfor %}
            </div>
        </div>
        
        <div>
            <div class="single_div" id="reptiles">
                <h3>Reptiles</h3>

                {% for org in organism_list|filter_by_taxonomy:'Reptile' %}
                    <ul><a href="{{ org.get_absolute_url }}">{{ org.name }}</a></ul>
                {% endfor %}
            </div>

            <div class="single_div" id="lamprey">
                <h3>Lamprey</h3>

                {% for org in organism_list|filter_by_taxonomy:'Lamprey' %}
                    <ul><a href="{{ org.get_absolute_url }}">{{ org.name }}</a></ul>
                {% endfor %}
            </div>
        </div>
        {% endblock %}
    </body>
</html>

catalog/templates/index.html
{% extends "base-menu.html" %}

{% block title %}Home{% endblock %}


    {% block content %}
        
        <h1 id="homepage">The LRRCE Website</h1>
        
        {% load static %}
        <img id="homeimg" src="{% static 'img/Tree-small.png' %}">
        
        <div id="warning">
            <h3>N.B.</h3>
                <p><i>This site is still in a developmental version. As such, some features will not be fully functional whilst the project
                    is run on a development server (like the one provided by Django). Such as:</i></p>
                <ul id="warning_list">
                    <li>External links</li>
                    <li>Google powered search function</li>
                <ul>
        </div>
        
        <p>This site provides updated sequence information of SLRPs from classes A, I, II and III.</p>
        
        <!-- Google Custom Search Element -->
        <div id=”cse” style=”width:100%;”>Loading</div>
        <script src=”http://www.google.com/jsapi” type=”text/javascript”></script>
        <script type=”text/javascript”>google.load(‘search’, ‘1’);
          google.setOnLoadCallback(function(){var cse = new google.search.
          CustomSearchControl();cse.draw(‘cse’);}, true);</script>
        
        <h3>Reference:</h3>
        
        <p>LRRCE: a leucine-rich repeat cysteine capping motif unique to the chordate lineage <br>
            Hosil Park, Julie Huxley-Jones, Ray P Boot-Handford, Paul N Bishop, Teresa K Attwood and Jordi Bella<br>
        
            <!-- Possibly alter link below, i.e. change colour or underline etc. -->
            <a href="http://bmcgenomics.biomedcentral.com/articles/10.1186/1471-2164-9-599"><i>BMC</i> Genomics 2008, 9:599</a>
        </p>
        
        <h4>Comments, Errors, Suggestions</h4>
        
        <p>Please contact us:<br><a href="mailto: jordi.bella@manchester.ac.uk">jordi.bella@manchester.ac.uk</a></p>
        
        <p><strong>Last update:</strong> 17/04/2017</p>
        
    {% endblock %}